spring.application.name=hotel-booking

server.port=${PORT:8081}
server.forward-headers-strategy=framework
server.tomcat.threads.max=20

spring.mvc.format.date=iso

management.endpoints.web.exposure.include=health

springdoc.swagger-ui.use-root-path=true
